### ISSUE TITLE
automation: ensure all tutorials runs on latest fluvio release

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio-website#206]
All tutorial on master branch should run with dev release of fluvio.
All tutorial on stable branch should run with latest release of fluvio.

This should be part of website CI.

**Comment by ajhunyady** [comment]
Do we need to add versioning to your content?

**Comment by tjtelan** [comment]
> Do we need to add versioning to your content?

Not directly. We need a way to organize the code on the site so it is easier to run in a CI process.

Currently we manage the example code not unlike standard content. The consequence being our only option for accessing code in CI is to parse the markdown, or scrape the html if we want access to the code.

---

My first thought is that we're still going to need to do some code generation to "glue together code" because the tutorial is split up into several disjoint code blocks.

I think because our tutorial is has a pretty straightforward narrative, we can make a pattern for stitching things together. More moving pieces though.
